import apiflask.fields
from loguru import logger

from apiflask import Schema, fields
from apiflask.fields import String, Integer, List, Dict, Boolean, Raw
from apiflask.validators import Length, OneOf

category_field = String(required=True, description='Category the user subscribes to')


class CreateSubscription(Schema):
    category = category_field


class Subscription(CreateSubscription):
    id = String(required=True, description='Autogenerated id for identification')
    active = Boolean(required=True, description='Describes if the subscription is active or not')


class UserSubscriptionList(Schema):
    user_id = fields.String()
    subscriptions = fields.List(fields.Nested(Subscription))


class UsersList(Schema):
    users = List(fields.String())

