import apiflask.fields
from loguru import logger

from apiflask import Schema, fields
from apiflask.fields import String, Integer, List, Dict, Boolean, Raw
from apiflask.validators import Length, OneOf
# from marshmallow_toplevel import TopLevelSchema


class CreateSubscription(Schema):
    category = String(required=True, description='Category the user subscribes to')


class Subscription(CreateSubscription):
    id = String(required=True, description='Autogenerated id for identification')
    # category = String(required=True, description='Category the user subscribes to')
    active = Boolean(required=True, description='Describes if the subscription is active or not')


class UserSubscriptionList(Schema):
    user_id = List(fields.Nested(Subscription))



